### ISSUE TITLE
Deployar

### ISSUE THREAD

**Issue by eduardomoroni** [project-australia/Brisbane#7]
@hebertporto , teria como confirmar com o sydney se precisa mesmo deployar o app mobile pra store?
Talvez podemos usar o https://appetize.io/ e mandar para ele uma preview.

**Comment by eduardomoroni** [comment]
https://appetize.io/app/ua01c4evxkexv6mp7873w0b010?device=iphone6s&scale=75&orientation=portrait&osVersion=11.1

**Comment by hebertporto** [comment]
Já perguntei, depois manda o resultado aqui.

**Comment by eduardomoroni** [comment]
https://github.com/project-australia/Brisbane/pull/13
